### ISSUE TITLE
Fix personal email address in Constant.java

### ISSUE THREAD

**Issue by alexcg1** [newtonproject/NewPaySDK-Android#4]
Should change to a company address /assign @weixuefeng

**Comment by alexcg1** [comment]
Also check other files. I see it in Environment.java too...

**Comment by alexcg1** [comment]
And app/src/main/java/com/newmall/MainFragment.java

**Comment by xiawu** [comment]
@weixuefeng follow this issue

**Comment by weixuefeng** [comment]
@alexcg1 weixufeng@lubangame.com is also company address.
